name: Build pack
on:
  push:
jobs:
  build:
    name: Build pack
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        run: |
          curl -Lo packsquash.zip https://github.com/ComunidadAylas/PackSquash/releases/download/v0.4.1/packsquash-x86_64-unknown-linux-gnu.zip
          unzip packsquash.zip -d /usr/local/bin
          chmod +x /usr/local/bin/packsquash
          packsquash -v
          ./gradlew packsquash
      - name: Calculate SHA1
        run: |
          echo "PACK_SHA1=$(sha1sum build/packsquash/SG.zip | cut --delimiter " " --fields 1)" >> "$GITHUB_ENV"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SG.zip
          path: build/packsquash/SG.zip
      - name: Tag and create release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          description: "SHA1: ${{ env.PACK_SHA1 }}"
          tag_name: master-v${{ github.run_number }}
          files: build/packsquash/SG.zip